<template>
  <v-container fluid class="page">
    <section class="hero mb-5">
      <div><span>AI SIGNAL SOURCES</span><h1>AI 信号源</h1><p>独立运行、可复用的 AI 分析服务。策略只负责引用并形成交易决策。</p></div>
      <div class="d-flex ga-2 flex-wrap"><v-btn color="secondary" prepend-icon="mdi-chart-timeline-variant-shimmer" @click="openCreate('2.0')">新建 2.0 结构化信号源</v-btn><v-btn color="secondary" variant="outlined" prepend-icon="mdi-text-box-edit-outline" @click="openCreate('1.0')">新建 1.0 自定义信号源</v-btn></div>
    </section>
    <v-alert v-if="message" :type="messageType" variant="tonal" class="mb-4" closable @click:close="message = ''">{{ message }}</v-alert>
    <v-row>
      <v-col v-for="item in sources" :key="item.signal_source_id" cols="12" md="6" xl="4">
        <v-card class="source-card" elevation="0">
          <v-card-text>
            <div class="d-flex justify-space-between ga-2"><div><span class="eyebrow">{{ item.symbol }} · {{ item.period }}</span><h2>{{ item.name }}</h2></div><v-chip :color="item.enabled ? 'success' : 'grey'" size="small">{{ item.enabled ? '运行中' : '已停用' }}</v-chip></div>
            <p>{{ item.config.model || '未选择模型' }} · 每 {{ item.config.analysis_interval_minutes || '-' }} 分钟分析</p>
            <div class="chips"><v-chip size="x-small" variant="tonal">信号源 {{ item.config.signal_source_version || '1.0' }}</v-chip><v-chip size="x-small" variant="tonal">{{ item.config.kline_count || '-' }} 根K线</v-chip><v-chip v-if="item.config.signal_source_version === '2.0'" size="x-small" :color="item.config.adaptive_enabled !== false ? 'primary' : 'grey'" variant="tonal">自适应{{ item.config.adaptive_enabled !== false ? '开启' : '关闭' }} · {{ item.config.adaptive_sample_size || 7 }}笔/SETUP</v-chip><v-chip v-if="item.config.analysis_paused" size="x-small" color="warning" variant="tonal">分析已暂停</v-chip><v-chip v-if="item.share_runtime_data" size="x-small" color="success" variant="tonal">已共享运行数据</v-chip><v-chip v-if="item.locked" size="x-small" color="warning" variant="tonal">已冻结</v-chip></div>
            <p v-if="item.locked" class="lock-note">已被其他用户引用或被已部署策略使用。不可修改、停用或删除，可复制新版本。</p>
          </v-card-text>
          <v-card-actions><v-btn size="small" variant="text" prepend-icon="mdi-content-copy" @click="copy(item)">复制</v-btn><v-btn v-if="item.config.signal_source_version === '2.0'" size="small" variant="text" :loading="adaptiveId === item.signal_source_id" @click="toggleAdaptive(item)">{{ item.config.adaptive_enabled !== false ? '关闭自适应' : '开启自适应' }}</v-btn><v-btn size="small" :color="item.config.analysis_paused ? 'success' : 'warning'" variant="text" :loading="pausingId === item.signal_source_id" @click="togglePause(item)">{{ item.config.analysis_paused ? '恢复分析' : '暂停分析' }}</v-btn><v-spacer/><v-btn size="small" variant="text" :disabled="item.locked" @click="openEdit(item)">编辑</v-btn><v-btn size="small" color="error" variant="text" :disabled="item.locked" @click="remove(item)">删除</v-btn></v-card-actions>
        </v-card>
      </v-col>
    </v-row>
    <div v-if="!loading && !sources.length" class="empty"><v-icon size="52">mdi-brain</v-icon><h2>还没有 AI 信号源</h2><p>先创建一个独立信号源，再在策略中选择它。</p></div>
    <v-dialog v-model="dialog" max-width="820" persistent :class="{ 'is-v1': form.config.signal_source_version === '1.0', 'is-v2': form.config.signal_source_version === '2.0' }"><v-card>
      <v-card-title class="d-flex align-center ga-2">{{ form.signal_source_id ? '编辑 AI 信号源' : '新建 AI 信号源' }}<v-chip size="small" variant="tonal">信号源 {{ form.config.signal_source_version }}</v-chip></v-card-title>
      <v-card-text><v-row>
        <v-col cols="12" md="4"><v-text-field v-model="form.name" label="名称"/></v-col><v-col cols="12" md="4"><v-select v-model="form.symbol" :items="options.symbols" label="交易品种" clearable/></v-col><v-col cols="12" md="4"><v-select v-model="form.period" :items="periods" label="分析周期"/></v-col>
        <v-col cols="12" md="4"><v-select v-model="form.config.model" :items="options.models" label="运行模型"/></v-col><v-col cols="12" md="4"><v-select v-model.number="form.config.analysis_interval_minutes" :items="intervalOptions" label="调用间隔（分钟）"/></v-col><v-col cols="12" md="4"><v-select v-model="form.config.forecast_horizon_bars" :items="horizonOptions" label="未来观察窗口" hint="自动根据调度周期和分析周期计算" persistent-hint/></v-col><v-col cols="12" md="4"><v-text-field v-model.number="form.config.kline_count" label="分析 K 线数量" type="number" min="10" max="288" hint="最多 288 根，与 EA 全量初始化数据一致" persistent-hint/></v-col><v-col v-if="form.config.signal_source_version === '2.0'" cols="12" md="4"><v-select v-model="form.config.analysis_template" :items="structureTemplates" label="结构分析模板" hint="系统先识别背景趋势，再识别动态局部箱体/趋势结构" persistent-hint/></v-col>
        <v-col v-if="form.config.signal_source_version === '2.0'" cols="12"><v-card variant="tonal" color="primary" class="structure-settings"><v-card-title class="text-subtitle-1">箱体确认参数</v-card-title><v-card-text><div class="text-caption text-medium-emphasis mb-3">系统先按这些参数计算候选箱体，再交给大模型结合原始K线确认。默认值适合大多数品种，可按品种波动特征调整。</div><v-row><v-col cols="12" sm="6" md="2"><v-text-field v-model.number="form.config.range_min_touches" label="每侧最少触碰" type="number" min="1" max="5" suffix="次" hint="上下沿各自至少触碰次数" persistent-hint/></v-col><v-col cols="12" sm="6" md="2"><v-text-field v-model.number="rangeInsidePercent" label="最低箱体内部比例" type="number" min="50" max="100" suffix="%" hint="收盘价在箱体内的比例" persistent-hint/></v-col><v-col cols="12" sm="6" md="2"><v-text-field v-model.number="form.config.range_tolerance_atr_multiplier" label="ATR容差倍数" type="number" min="0.1" max="3" step="0.05" suffix="×" hint="边界触碰容差" persistent-hint/></v-col><v-col cols="12" sm="6" md="2"><v-text-field v-model.number="rangeToleranceWidthPercent" label="宽度容差比例" type="number" min="0.5" max="20" step="0.5" suffix="%" hint="箱体宽度的最低容差" persistent-hint/></v-col><v-col cols="12" sm="6" md="2"><v-text-field v-model.number="form.config.range_min_width_atr" label="最小箱体宽度" type="number" min="0" max="20" step="0.5" suffix="ATR" hint="过滤过窄箱体" persistent-hint/></v-col><v-col cols="12" sm="6" md="2"><v-text-field v-model.number="form.config.range_max_width_atr" label="最大箱体宽度" type="number" min="1" max="50" step="0.5" suffix="ATR" hint="过滤过宽箱体" persistent-hint/></v-col></v-row></v-card-text></v-card></v-col>
        <v-col v-if="form.config.signal_source_version === '2.0'" cols="12"><v-card variant="outlined" class="adaptive-settings"><v-card-text class="d-flex align-center flex-wrap ga-4"><v-switch v-model="form.config.adaptive_enabled" color="primary" inset hide-details label="允许自适应调参"/><v-select v-model.number="form.config.adaptive_sample_size" :items="[7,10,20,30,50]" label="每种 SETUP 最近订单数" density="compact" hide-details style="max-width:230px"/><span class="text-caption text-medium-emphasis">默认开启。仅按同一信号源、同一 SETUP 的已平仓订单统计；默认取最近7笔，同一批样本不会重复调整。</span></v-card-text></v-card></v-col>
        <v-col cols="12">
          <div class="reference-header"><div><div class="section-label">行情上下文</div><div class="reference-help">参考行情可选，只辅助当前主周期分析，不会单独产生信号，也不会增加大模型调用次数。</div></div><v-btn size="small" variant="tonal" color="primary" prepend-icon="mdi-plus" :disabled="references.length >= 5" @click="addReference">添加参考行情</v-btn></div>
          <v-alert v-if="form.config.signal_source_version === '2.0'" variant="tonal" color="primary" density="compact" class="mt-3 automatic-background">
            <div><strong>系统自动带入高周期背景</strong></div>
            <div v-if="automaticBackgroundPeriods.length">
              主行情为 {{ form.symbol || '主品种' }} / {{ form.period }}；运行时自动附带用户共享行情域内同一品种的
              {{ automaticBackgroundPeriods.join('、') }} K线，每个背景周期最多 100 根。
            </div>
            <div v-else>当前主周期没有更高的自动背景周期。</div>
            <div class="mt-1">自动背景只用于判断顺势、逆势和结构确认，不会独立生成交易建议；与下方手工参考行情重复时系统会自动去重。</div>
          </v-alert>
          <v-alert v-else-if="!references.length" variant="tonal" color="grey" density="compact" class="mt-3">当前未配置参考行情，信号源仅使用 {{ form.symbol || '主品种' }} / {{ form.period }}。</v-alert>
          <div v-for="(reference, index) in references" :key="`${reference.symbol}-${reference.period}-${index}`" class="reference-row mt-3"><v-select v-model="reference.symbol" :items="referenceSymbols" label="参考品种" density="compact" hide-details="auto" @update:model-value="normalizeReferencePeriod(reference)"/><v-select v-model="reference.period" :items="referencePeriodOptions(reference)" label="参考周期" density="compact" hide-details="auto"/><v-text-field v-model.number="reference.kline_count" label="K线数量" type="number" min="10" max="288" density="compact" hide-details="auto"/><v-select v-model="reference.role" :items="referenceRoles" label="用途" density="compact" hide-details="auto"/><v-btn icon="mdi-delete-outline" variant="text" color="error" @click="removeReference(index)"/></div>
        </v-col>
        <v-col cols="12"><div class="prompt-builder"><div class="section-label">分析目标与专属提示词</div><div class="reference-help">告诉 AI 你希望重点识别的行情特征。可选择最多 3 个已开放模型生成候选并对比；每个候选会消耗 1 次低频调用额度。</div><v-alert v-if="options.runtimeContract.runtime_variables?.length" variant="tonal" color="primary" density="compact" class="mt-3 runtime-contract"><div class="contract-title">运行时数据与策略输出约定</div><div v-for="variable in options.runtimeContract.runtime_variables" :key="variable.name" class="contract-row"><code>{{ variable.name }}</code><span>{{ variable.required ? '必填' : '可选' }}：{{ variable.description }} 字段：{{ variable.fields.join(', ') }}</span></div><div class="contract-row"><strong>模型输出</strong><span>{{ options.runtimeContract.output_contract.top_level }} 必填：{{ options.runtimeContract.output_contract.required.join('；') }}</span></div><div class="contract-row"><strong>交易建议</strong><span>{{ options.runtimeContract.output_contract.trade_suggestion.join('、') }}。{{ options.runtimeContract.output_contract.price_rules.join('；') }}</span></div><div class="contract-row"><strong>策略处理</strong><span>{{ options.runtimeContract.strategy_usage.join(' ') }}</span></div></v-alert><v-textarea v-model="promptIntent" class="mt-3" label="例如：关注亚洲盘突破后的延续；M5 只用于确认大方向" rows="3" auto-grow counter="2000"/><v-select v-model="promptModels" :items="options.promptGenerationModels" label="提示词生成模型（可多选对比）" multiple chips closable-chips :hint="`最多选择 3 个；未选择时使用场景默认模型。${promptModels.length ? ` 已选 ${promptModels.length} 个` : ''}`" persistent-hint class="mt-2"/><div class="d-flex align-center ga-3 mt-3"><v-btn color="primary" variant="tonal" prepend-icon="mdi-auto-fix" :loading="generatingPrompt" :disabled="!canGeneratePrompt" @click="generatePrompt">{{ promptModels.length > 1 ? '生成并对比候选' : '生成提示词候选' }}</v-btn><span v-if="form.config.analysis_prompt_template" class="text-caption text-medium-emphasis">当前已使用专属提示词</span><span v-else class="text-caption text-warning">请先生成并应用一份专属提示词后保存</span></div><v-row v-if="promptCandidates.length" class="mt-1"><v-col v-for="candidate in promptCandidates" :key="candidate.model" cols="12" :md="promptCandidates.length > 1 ? 6 : 12"><v-card variant="outlined" class="prompt-candidate h-100"><v-card-text><div class="d-flex align-center justify-space-between ga-3"><div><strong>{{ candidate.model }}</strong><p v-if="candidate.summary">{{ candidate.summary }}</p></div><v-btn color="success" size="small" @click="applyPromptCandidate(candidate)">应用此候选</v-btn></div><v-alert v-if="candidate.assumptions?.length" type="info" variant="tonal" density="compact" class="my-3">{{ candidate.assumptions.join('；') }}</v-alert><v-textarea v-model="candidate.system_prompt" label="System Prompt" rows="4" auto-grow class="mt-3"/><v-textarea v-model="candidate.analysis_prompt_template" label="分析提示词模板" rows="10" auto-grow class="mt-2"/></v-card-text></v-card></v-col></v-row></div></v-col>
        <v-col cols="12"><v-switch v-model="form.share_runtime_data" color="success" inset label="共享运行数据" hint="仅共享分析结论和可见参数，不共享提示词与模型配置。" persistent-hint/></v-col>
      </v-row></v-card-text>
      <v-card-actions><v-spacer/><v-btn variant="text" @click="dialog=false">取消</v-btn><v-btn color="primary" :loading="saving" @click="save">保存</v-btn></v-card-actions>
    </v-card></v-dialog>
  </v-container>
</template>

<script setup>
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { marketAPI } from '@/api/market'

const periods = ['M1', 'M5', 'M15', 'H1', 'H4']
const sourceVersions = [{ title: '2.0 结构化模板', value: '2.0' }, { title: '1.0 自定义提示词', value: '1.0' }]
const structureTemplates = [{ title: '自动识别：背景趋势 + 动态局部结构', value: 'auto_structure' }, { title: '箱体优先', value: 'range' }, { title: '趋势回调优先', value: 'trend_pullback' }, { title: '收敛三角形', value: 'converging_triangle' }, { title: '扩散三角形', value: 'diverging_triangle' }]
const horizonOptions = [{ title: '自动', value: 0 }, ...[6, 10, 20, 30, 48].map(value => ({ title: `${value} 根`, value }))]
const defaultPromptIntent = '识别主周期趋势、行情状态和关键支撑压力位，并输出可由实时 Tick 后续评估的结构化交易计划：区间在边界交易，趋势在回调或反抽时顺势交易。'
const defaultSystemPrompt = '你是一位专业的技术分析师。只能依据提供的主品种、主周期 K 线判断趋势、关键价位和交易机会；参考行情只能辅助确认，不能独立产生结论。只返回严格、完整的 JSON 对象，不得输出解释、推理过程或 Markdown。交易建议必须遵守模板字段与价格规则；只有条件不足以形成可辩护的结构化交易计划时才返回空数组。'
const defaultAnalysisPromptTemplate = '请分析主品种的主周期 K 线，只返回严格 JSON，顶层键必须为实际主品种名称。\n\n主行情 K 线：\n{{market_data}}\n\n当前可交易参考价：\n{{current_price}}\n当前价格只用于理解市场位置和风险，不要求 entry_price 接近当前价；策略会在后续实时 Tick 接近 entry_price 时再评估入场。\n\n可选参考行情：\n{{reference_market_data}}\n参考行情为空时忽略本节；它只能辅助主行情判断，不能单独产生趋势或交易建议。\n\n规则：\n1. 必须输出主周期的 trend_analysis、overall_trend、key_levels 和 trade_suggestions。\n2. trade_suggestions 是由 K 线结构得出的未来价格计划；只有不存在可辩护计划时才返回 []。\n3. 区间震荡：可在确认支撑附近给 buy、确认压力附近给 sell；止损放在区间外，止盈指向另一侧。即使当前价格在区间中部，仍可给出这些未来边界计划。\n4. 单边上涨：在上涨结构未失效时，可给出回调或回踩至趋势线/支撑的 buy 计划；stop_loss 放在结构失效位下方，take_profit 指向趋势延续目标。\n5. 单边下跌：在下跌结构未失效时，可给出反抽至压力/趋势线的 sell 计划；stop_loss 放在结构失效位上方，take_profit 指向趋势延续目标。\n6. buy 必须满足 stop_loss < entry_price < take_profit；sell 必须满足 take_profit < entry_price < stop_loss。\n\n输出：\n{"实际主品种":{"trend_analysis":{"主周期":{"trend":"趋势类型","confidence":68,"reason":"K线判断理由"}},"overall_trend":{"direction":"up|down|sideways","strength":0,"summary":"行情结论"},"key_levels":{"resistance":[0,0,0],"support":[0,0,0]},"trade_suggestions":[{"signal_source_id":"当前信号源ID","period":"主周期","direction":"buy|sell","confidence":68,"entry_price":0,"stop_loss":0,"take_profit":0,"reason":"结构化交易计划理由"}]}}\n不要输出 Markdown、思考过程、策略 ID 或额外字段。'
const defaultPromptCandidate = () => ({ model: '结构化交易计划默认候选', system_prompt: defaultSystemPrompt, analysis_prompt_template: defaultAnalysisPromptTemplate, summary: '基于主周期趋势、关键价位和未来入场计划的通用模板，可由策略在后续实时 Tick 中评估。', assumptions: ['只分析主品种和主周期', '参考行情仅辅助主行情判断', '没有可辩护的结构化计划时才返回空交易建议'] })
const sources = ref([]), loading = ref(false), saving = ref(false), dialog = ref(false), message = ref(''), messageType = ref('success'), loadingOptions = ref(false), generatingPrompt = ref(false), pausingId = ref(''), adaptiveId = ref(''), promptIntent = ref(defaultPromptIntent), promptModels = ref([]), promptCandidates = ref([])
const options = reactive({ models: [], promptGenerationModels: [], symbols: [], marketDataAccounts: [], system: '', prompt: '', runtimeContract: { runtime_variables: [], output_contract: {}, strategy_usage: [] } })
const emptyForm = () => ({ signal_source_id: '', name: '', market_data_account_id: 0, symbol: '', period: 'M5', enabled: true, share_runtime_data: false, config: { signal_source_version: '2.0', analysis_template: 'auto_structure', analysis_mode: 'self_analysis', model: '', analysis_interval_minutes: 5, forecast_horizon_bars: 0, kline_count: 288, range_min_touches: 3, range_min_inside_ratio: 0.80, range_tolerance_atr_multiplier: 0.60, range_tolerance_width_ratio: 0.02, range_min_width_atr: 2, range_max_width_atr: 6, adaptive_enabled: true, adaptive_sample_size: 7, prompt_mode: 'structured', reference_runtime_ids: [], reference_market_data: [], system_prompt: defaultSystemPrompt, analysis_prompt_template: defaultAnalysisPromptTemplate } })
const form = reactive(emptyForm())
const rangeInsidePercent = computed({ get: () => Math.round(Number(form.config.range_min_inside_ratio || 0.80) * 100), set: value => { form.config.range_min_inside_ratio = Number(value || 80) / 100 } })
const rangeToleranceWidthPercent = computed({ get: () => Number(form.config.range_tolerance_width_ratio || 0.02) * 100, set: value => { form.config.range_tolerance_width_ratio = Number(value || 2) / 100 } })
const intervalOptions = computed(() => [1,2,3,5,10,15,30,60,120,240,480,720,1440].filter(value => value >= ({ M1: 1, M5: 5, M15: 15, H1: 60, H4: 240 }[form.period] || 1)).map(value => ({ title: `${value} 分钟`, value })))
const referenceRoles = [{ title: '高周期确认', value: 'higher_timeframe' }, { title: '低周期确认', value: 'lower_timeframe' }, { title: '相关品种', value: 'related_symbol' }, { title: '市场上下文', value: 'market_context' }]
const references = computed(() => form.config.reference_market_data || [])
const automaticBackgroundPeriods = computed(() => ({
  M1: ['M5', 'M15'],
  M5: ['M15', 'H1'],
  M15: ['H1', 'H4'],
  H1: ['H4'],
  H4: [],
}[form.period] || []))
// 同品种的其他周期也是有效的参考行情；只有同品种时排除主分析周期。
const referenceSymbols = computed(() => Array.from(new Set([form.symbol, ...options.symbols].filter(Boolean))))
function referencePeriodOptions (reference) {
  const current = String(reference?.period || '')
  const isSameSymbol = String(reference?.symbol || '').trim().toUpperCase() === String(form.symbol || '').trim().toUpperCase()
  return periods.filter(period => !isSameSymbol || period !== form.period || period === current)
}
const canGeneratePrompt = computed(() => form.config.signal_source_version === '1.0' && Boolean(form.symbol && form.period && promptIntent.value.trim() && promptModels.value.length <= 3))
const clone = value => JSON.parse(JSON.stringify(value))
async function load () { loading.value = true; try { sources.value = (await marketAPI.getAISignalSources()).items || [] } catch (e) { messageType.value='error'; message.value=e.response?.data?.detail || '加载信号源失败' } finally { loading.value=false } }
async function loadOptions () { loadingOptions.value=true; try { const data=await marketAPI.getLLMSignalOptions(form.symbol || null); options.models=data.models||[]; options.promptGenerationModels=data.prompt_generation_models||[]; options.symbols=data.symbols||[]; form.market_data_account_id=0; options.system=data.default_system_prompt||''; options.prompt=data.default_analysis_prompt_template||''; options.runtimeContract=data.runtime_contract || { runtime_variables: [], output_contract: {}, strategy_usage: [] } } finally { loadingOptions.value=false } }
function openCreate (version = '2.0') { Object.assign(form, emptyForm()); form.config.signal_source_version=version; form.config.analysis_template=version === '2.0' ? 'auto_structure' : 'custom'; form.config.prompt_mode=version === '2.0' ? 'structured' : 'custom'; promptIntent.value=defaultPromptIntent; promptModels.value=[]; promptCandidates.value=version === '1.0' ? [defaultPromptCandidate()] : []; dialog.value=true; loadOptions() }
function openEdit (item) { Object.assign(form, clone(item)); form.config ||= {}; form.config.signal_source_version ||= '1.0'; form.config.analysis_template ||= form.config.signal_source_version === '2.0' ? 'auto_structure' : 'custom'; form.config.forecast_horizon_bars = Number(form.config.forecast_horizon_bars || 0); form.config.range_min_touches = Number(form.config.range_min_touches || 3); form.config.range_min_inside_ratio = Number(form.config.range_min_inside_ratio || 0.80); form.config.range_tolerance_atr_multiplier = Number(form.config.range_tolerance_atr_multiplier || 0.60); form.config.range_tolerance_width_ratio = Number(form.config.range_tolerance_width_ratio || 0.02); form.config.range_min_width_atr = Number(form.config.range_min_width_atr || 2); form.config.range_max_width_atr = Number(form.config.range_max_width_atr || 6); form.config.adaptive_enabled = form.config.adaptive_enabled !== false; form.config.adaptive_sample_size = Number(form.config.adaptive_sample_size || 7); form.config.reference_market_data ||= []; form.config.prompt_mode=form.config.signal_source_version === '2.0' ? 'structured' : 'custom'; promptIntent.value=defaultPromptIntent; promptModels.value=[]; const currentCandidate = { model: form.config.signal_source_version === '1.0' ? '1.0 默认模板（可编辑）' : '2.0 系统模板', system_prompt: form.config.system_prompt || defaultSystemPrompt, analysis_prompt_template: form.config.analysis_prompt_template || defaultAnalysisPromptTemplate, summary: form.config.signal_source_version === '1.0' ? '系统默认 1.0 模板，可直接修改后保存。' : '系统内置结构化模板。', assumptions: [] }; promptCandidates.value=form.config.signal_source_version === '2.0' ? [] : [currentCandidate]; dialog.value=true; loadOptions() }
function normalizeReferencePeriod (reference) {
  if (!reference || String(reference.symbol || '').trim().toUpperCase() !== String(form.symbol || '').trim().toUpperCase()) return
  if (reference.period !== form.period) return
  reference.period = periods.find(period => period !== form.period) || form.period
}
function addReference () {
  if (references.value.length >= 5) return
  const symbol = form.symbol || referenceSymbols.value[0] || ''
  const period = periods.find(value => value !== form.period) || form.period
  references.value.push({ symbol, period, kline_count: 100, role: 'market_context' })
}
function removeReference (index) { references.value.splice(index, 1) }
async function generatePrompt () { generatingPrompt.value=true; try { const data=clone(form); data.config.reference_market_data=(data.config.reference_market_data || []).filter(item => item.symbol && item.period); const result=await marketAPI.generateAISignalPrompt({ ...data, intent: promptIntent.value.trim(), model_ids: promptModels.value }); promptCandidates.value=result.candidates || (result.candidate ? [result.candidate] : []); messageType.value='success'; message.value=promptCandidates.value.length > 1 ? '已生成多个提示词候选，请对比后选择一份应用。' : '已根据当前信号源配置生成候选提示词，请预览后应用。' } catch(e) { messageType.value='error'; message.value=e.response?.data?.detail || '生成提示词候选失败' } finally { generatingPrompt.value=false } }
function applyPromptCandidate (candidate) { if (!candidate) return; form.config.prompt_mode='custom'; form.config.system_prompt=candidate.system_prompt; form.config.analysis_prompt_template=candidate.analysis_prompt_template; messageType.value='success'; message.value=`已应用 ${candidate.model || '候选'}，保存信号源后生效。` }
function syncLegacyPrompt () { const candidate = promptCandidates.value[0]; if (form.config.signal_source_version === '1.0' && candidate) { form.config.system_prompt = candidate.system_prompt; form.config.analysis_prompt_template = candidate.analysis_prompt_template } }
async function save () { saving.value=true; try { syncLegacyPrompt(); const data=clone(form); const minimum={M1:1,M5:5,M15:15,H1:60,H4:240}[data.period]||1; data.config.analysis_mode='self_analysis'; data.config.signal_source_version=data.config.signal_source_version || '2.0'; data.config.analysis_template=data.config.analysis_template || 'auto_structure'; data.config.analysis_interval_minutes=Math.max(minimum, Number(data.config.analysis_interval_minutes) || 0); data.config.kline_count=Math.max(10, Math.min(288, Number(data.config.kline_count) || 100)); data.config.range_min_touches=Math.max(1, Math.min(5, Number(data.config.range_min_touches) || 3)); data.config.range_min_inside_ratio=Math.max(0.5, Math.min(1, Number(data.config.range_min_inside_ratio) || 0.80)); data.config.range_tolerance_atr_multiplier=Math.max(0.1, Math.min(3, Number(data.config.range_tolerance_atr_multiplier) || 0.60)); data.config.range_tolerance_width_ratio=Math.max(0.005, Math.min(0.2, Number(data.config.range_tolerance_width_ratio) || 0.02)); data.config.range_min_width_atr=Math.max(0, Math.min(20, Number(data.config.range_min_width_atr) || 2)); data.config.range_max_width_atr=Math.max(data.config.range_min_width_atr, Math.min(50, Number(data.config.range_max_width_atr) || 6)); data.config.adaptive_enabled=data.config.adaptive_enabled !== false; data.config.adaptive_sample_size=Math.max(5, Math.min(50, Number(data.config.adaptive_sample_size) || 7)); data.config.reference_market_data=(data.config.reference_market_data || []).filter(item => item.symbol && item.period).map(item => ({ ...item, kline_count: Math.max(10, Math.min(288, Number(item.kline_count) || 100)) })); data.config.prompt_mode=data.config.signal_source_version === '2.0' ? 'structured' : 'custom'; if (data.config.signal_source_version === '1.0' && (!data.config.system_prompt || !data.config.analysis_prompt_template)) throw new Error('1.0 默认提示词初始化失败，请重试'); const result=data.signal_source_id ? await marketAPI.updateAISignalSource(data.signal_source_id,data) : await marketAPI.createAISignalSource(data); dialog.value=false; messageType.value='success'; message.value=result.source?.locked ? '已保存并冻结' : 'AI 信号源已保存'; await load() } catch(e) { messageType.value='error'; message.value=e.response?.data?.detail || '保存失败' } finally { saving.value=false } }
async function toggleAdaptive (item) { adaptiveId.value=item.signal_source_id; try { const enabled=item.config?.adaptive_enabled === false; await marketAPI.configureAISignalAdaptive(item.signal_source_id,enabled,item.config?.adaptive_sample_size||7); messageType.value='success'; message.value=`自适应调参已${enabled?'开启':'关闭'}并热加载`; await load() } catch(e) { messageType.value='error'; message.value=e.response?.data?.detail||'调整自适应设置失败' } finally { adaptiveId.value='' } }
async function copy (item) { try { await marketAPI.copyAISignalSource(item.signal_source_id); messageType.value='success'; message.value='已创建可修改的新副本'; await load() } catch(e) { messageType.value='error'; message.value=e.response?.data?.detail || '复制失败' } }
async function togglePause (item) {
  const paused = !item.config?.analysis_paused
  if (!paused) {
    pausingId.value = item.signal_source_id
    try { await marketAPI.pauseAISignalSource(item.signal_source_id, false); messageType.value='success'; message.value='AI 行情分析已恢复'; await load() } catch (e) { messageType.value='error'; message.value=e.response?.data?.detail || '恢复分析失败' } finally { pausingId.value='' }
    return
  }
  try {
    const impact = await marketAPI.getAISignalSourceImpact(item.signal_source_id)
    const rows = impact.items || []
    const users = Array.from(new Set(rows.map(row => row.username).filter(Boolean)))
    const strategies = rows.map(row => `${row.strategy_name || row.strategy_id}（${row.execution_mode === 'live' ? '实盘' : '模拟盘'}，${row.username || '未知用户'}，${row.deployment_status === 'active' ? '运行中' : row.deployment_status === 'paused' ? '已暂停' : '已结束'}）`)
    const detail = strategies.length ? `\n\n受影响策略：\n${strategies.join('\n')}` : '\n\n当前没有已部署策略引用此信号源。'
    if (!window.confirm(`暂停“${item.name}”的 AI 行情分析？\n\n将停止后续大模型分析和策略消费，已有分析快照保留。\n受影响用户：${users.length ? users.join('、') : '无'}${detail}`)) return
    pausingId.value = item.signal_source_id
    await marketAPI.pauseAISignalSource(item.signal_source_id, true)
    messageType.value='success'; message.value='AI 行情分析已暂停，影响范围已记录'; await load()
  } catch (e) { messageType.value='error'; message.value=e.response?.data?.detail || '暂停分析失败' } finally { pausingId.value='' }
}
async function remove (item) { if (!confirm(`删除“${item.name}”吗？`)) return; try { await marketAPI.deleteAISignalSource(item.signal_source_id); await load() } catch(e) { messageType.value='error'; message.value=e.response?.data?.detail || '删除失败' } }
watch(() => form.period, () => { const minimum={M1:1,M5:5,M15:15,H1:60,H4:240}[form.period]||1; form.config.analysis_interval_minutes=Math.max(Number(form.config.analysis_interval_minutes)||0, minimum) })
onMounted(load)
</script>

<style scoped>
.page{max-width:1500px;padding:28px}.hero{display:flex;align-items:center;justify-content:space-between;gap:24px;padding:28px 30px;border-radius:22px;color:#f7fcfa;background:radial-gradient(circle at 84% 16%,rgba(249,193,78,.3),transparent 26%),linear-gradient(125deg,#153e36,#13735c)}.hero span,.eyebrow{font-size:.72rem;font-weight:800;letter-spacing:.14em;color:#f2c768}.hero h1{margin:4px 0 7px;font-size:2.35rem}.hero p{margin:0;color:rgba(255,255,255,.78)}.source-card{height:100%;border:1px solid #dbe8e1;border-radius:18px;background:linear-gradient(145deg,#fff,#f7fbf8)}.source-card h2{margin:4px 0 8px;font-size:1.25rem;color:#1f4f42}.source-card p{min-height:38px;color:#60736b;font-size:.84rem}.chips{display:flex;flex-wrap:wrap;gap:6px}.lock-note{min-height:0!important;color:#9b6818!important}.empty{padding:90px 20px;text-align:center;color:#60736b}.empty h2{color:#294f42}.reference-header{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;padding-top:8px}.section-label{font-weight:700;color:#315f50}.reference-help{margin-top:4px;color:#71837b;font-size:.82rem}.reference-row{display:grid;grid-template-columns:1.2fr .8fr .8fr 1fr auto;gap:10px;align-items:center;padding:12px;border:1px solid #dce9e2;border-radius:12px;background:#f7fbf8}.prompt-builder{padding:16px;border:1px solid #dce9e2;border-radius:14px;background:linear-gradient(145deg,#fbfdfb,#f1f8f4)}.runtime-contract{line-height:1.45}.contract-title{font-weight:700;margin-bottom:6px}.contract-row{display:flex;gap:8px;margin-top:5px;align-items:flex-start}.contract-row code{white-space:nowrap;font-weight:700}.contract-row strong{white-space:nowrap}.prompt-candidate p{margin:4px 0 0;color:#60736b;font-size:.82rem}.prompt-candidate summary{cursor:pointer;color:#1f6a52;font-size:.82rem;font-weight:700}.prompt-candidate pre{max-height:260px;overflow:auto;padding:12px;border-radius:10px;background:#102c24;color:#e0f3e9;font-size:.72rem;white-space:pre-wrap}@media(max-width:850px){.reference-row{grid-template-columns:1fr 1fr}.reference-row .v-btn{justify-self:end}}@media(max-width:700px){.page{padding:16px}.hero{align-items:stretch;flex-direction:column}.hero h1{font-size:1.9rem}.contract-row{display:block}.contract-row code,.contract-row strong{display:block;margin-bottom:2px}}\n+.is-v2 .prompt-builder > .reference-help,.is-v2 .prompt-builder > .v-textarea,.is-v2 .prompt-builder > .v-select,.is-v2 .prompt-builder > .d-flex,.is-v2 .prompt-builder > .v-row{display:none!important}.is-v2 .prompt-builder{border-color:#b9d9ca}.is-v2 .prompt-builder:before{content:'2.0 使用系统内置结构化提示词，页面不再编辑或生成候选。';display:block;margin-bottom:10px;color:#1f6a52;font-size:.86rem;font-weight:600}
.is-v1 .prompt-builder > .reference-help,.is-v1 .prompt-builder > .v-textarea,.is-v1 .prompt-builder > .v-select,.is-v1 .prompt-builder > .d-flex{display:none!important}.is-v1 .prompt-builder{border-color:#d7c59a}.is-v1 .prompt-builder:before{content:'1.0 使用平台默认提示词，可直接编辑下方 System Prompt 和分析模板后保存。';display:block;margin-bottom:10px;color:#8a641b;font-size:.86rem;font-weight:600}.is-v1 .prompt-candidate .v-btn{display:none!important}.is-v2 .prompt-builder > .reference-help,.is-v2 .prompt-builder > .v-textarea,.is-v2 .prompt-builder > .v-select,.is-v2 .prompt-builder > .d-flex,.is-v2 .prompt-builder > .v-row{display:none!important}.is-v2 .prompt-builder{border-color:#b9d9ca}.is-v2 .prompt-builder:before{content:'2.0 使用系统内置结构化提示词，页面不再编辑或生成候选。';display:block;margin-bottom:10px;color:#1f6a52;font-size:.86rem;font-weight:600}
</style>
