<template>
  <v-container fluid class="page">
    <section class="hero mb-5">
      <div><span>AI SIGNAL SOURCES</span><h1>AI 信号源</h1><p>独立运行、可复用的 AI 分析服务。策略只负责引用并形成交易决策。</p></div>
      <v-btn color="secondary" prepend-icon="mdi-plus" @click="openCreate">新建信号源</v-btn>
    </section>
    <v-alert v-if="message" :type="messageType" variant="tonal" class="mb-4" closable @click:close="message = ''">{{ message }}</v-alert>
    <v-row>
      <v-col v-for="item in sources" :key="item.signal_source_id" cols="12" md="6" xl="4">
        <v-card class="source-card" elevation="0">
          <v-card-text>
            <div class="d-flex justify-space-between ga-2"><div><span class="eyebrow">{{ item.symbol }} · {{ item.period }}</span><h2>{{ item.name }}</h2></div><v-chip :color="item.enabled ? 'success' : 'grey'" size="small">{{ item.enabled ? '运行中' : '已停用' }}</v-chip></div>
            <p>{{ item.config.model || '未选择模型' }} · 每 {{ item.config.analysis_interval_minutes || '-' }} 分钟分析</p>
            <div class="chips"><v-chip size="x-small" variant="tonal">{{ item.config.kline_count || '-' }} 根K线</v-chip><v-chip v-if="item.share_runtime_data" size="x-small" color="success" variant="tonal">已共享运行数据</v-chip><v-chip v-if="item.locked" size="x-small" color="warning" variant="tonal">已冻结</v-chip></div>
            <p v-if="item.locked" class="lock-note">已被其他用户引用或被已部署策略使用。不可修改、停用或删除，可复制新版本。</p>
          </v-card-text>
          <v-card-actions><v-btn size="small" variant="text" prepend-icon="mdi-content-copy" @click="copy(item)">复制</v-btn><v-spacer/><v-btn size="small" variant="text" :disabled="item.locked" @click="openEdit(item)">编辑</v-btn><v-btn size="small" color="error" variant="text" :disabled="item.locked" @click="remove(item)">删除</v-btn></v-card-actions>
        </v-card>
      </v-col>
    </v-row>
    <div v-if="!loading && !sources.length" class="empty"><v-icon size="52">mdi-brain</v-icon><h2>还没有 AI 信号源</h2><p>先创建一个独立信号源，再在策略中选择它。</p></div>
    <v-dialog v-model="dialog" max-width="820" persistent><v-card>
      <v-card-title>{{ form.signal_source_id ? '编辑 AI 信号源' : '新建 AI 信号源' }}</v-card-title>
      <v-card-text><v-row>
        <v-col cols="12" md="4"><v-text-field v-model="form.name" label="名称"/></v-col><v-col cols="12" md="4"><v-select v-model="form.market_data_account_id" :items="options.marketDataAccounts" label="行情来源账户"/></v-col><v-col cols="12" md="2"><v-select v-model="form.symbol" :items="options.symbols" label="交易品种" clearable/></v-col><v-col cols="12" md="2"><v-select v-model="form.period" :items="periods" label="分析周期"/></v-col>
        <v-col cols="12" md="6"><v-select v-model="form.config.model" :items="options.models" label="运行模型"/></v-col><v-col cols="12" md="6"><v-select v-model.number="form.config.analysis_interval_minutes" :items="intervalOptions" label="调用间隔（分钟）"/></v-col><v-col cols="12" md="6"><v-text-field v-model.number="form.config.kline_count" label="分析 K 线数量" type="number" min="10" max="288" hint="最多 288 根，与 EA 全量初始化数据一致" persistent-hint/></v-col>
        <v-col cols="12">
          <div class="reference-header"><div><div class="section-label">行情上下文</div><div class="reference-help">参考行情可选，只辅助当前主周期分析，不会单独产生信号，也不会增加大模型调用次数。</div></div><v-btn size="small" variant="tonal" color="primary" prepend-icon="mdi-plus" :disabled="references.length >= 5" @click="addReference">添加参考行情</v-btn></div>
          <v-alert v-if="!references.length" variant="tonal" color="grey" density="compact" class="mt-3">当前未配置参考行情，信号源仅使用 {{ form.symbol || '主品种' }} / {{ form.period }}。</v-alert>
          <div v-for="(reference, index) in references" :key="`${reference.symbol}-${reference.period}-${index}`" class="reference-row mt-3"><v-select v-model="reference.symbol" :items="referenceSymbols" label="参考品种" density="compact" hide-details="auto" @update:model-value="normalizeReferencePeriod(reference)"/><v-select v-model="reference.period" :items="referencePeriodOptions(reference)" label="参考周期" density="compact" hide-details="auto"/><v-text-field v-model.number="reference.kline_count" label="K线数量" type="number" min="10" max="288" density="compact" hide-details="auto"/><v-select v-model="reference.role" :items="referenceRoles" label="用途" density="compact" hide-details="auto"/><v-btn icon="mdi-delete-outline" variant="text" color="error" @click="removeReference(index)"/></div>
        </v-col>
        <v-col cols="12"><div class="prompt-builder"><div class="section-label">分析目标与专属提示词</div><div class="reference-help">告诉 AI 你希望重点识别的行情特征。可选择最多 3 个已开放模型生成候选并对比；每个候选会消耗 1 次低频调用额度。</div><v-alert v-if="options.runtimeContract.runtime_variables?.length" variant="tonal" color="primary" density="compact" class="mt-3 runtime-contract"><div class="contract-title">运行时数据与策略输出约定</div><div v-for="variable in options.runtimeContract.runtime_variables" :key="variable.name" class="contract-row"><code>{{ variable.name }}</code><span>{{ variable.required ? '必填' : '可选' }}：{{ variable.description }} 字段：{{ variable.fields.join(', ') }}</span></div><div class="contract-row"><strong>模型输出</strong><span>{{ options.runtimeContract.output_contract.top_level }} 必填：{{ options.runtimeContract.output_contract.required.join('；') }}</span></div><div class="contract-row"><strong>交易建议</strong><span>{{ options.runtimeContract.output_contract.trade_suggestion.join('、') }}。{{ options.runtimeContract.output_contract.price_rules.join('；') }}</span></div><div class="contract-row"><strong>策略处理</strong><span>{{ options.runtimeContract.strategy_usage.join(' ') }}</span></div></v-alert><v-textarea v-model="promptIntent" class="mt-3" label="例如：关注亚洲盘突破后的延续；M5 只用于确认大方向" rows="3" auto-grow counter="2000"/><v-select v-model="promptModels" :items="options.promptGenerationModels" label="提示词生成模型（可多选对比）" multiple chips closable-chips :hint="`最多选择 3 个；未选择时使用场景默认模型。${promptModels.length ? ` 已选 ${promptModels.length} 个` : ''}`" persistent-hint class="mt-2"/><div class="d-flex align-center ga-3 mt-3"><v-btn color="primary" variant="tonal" prepend-icon="mdi-auto-fix" :loading="generatingPrompt" :disabled="!canGeneratePrompt" @click="generatePrompt">{{ promptModels.length > 1 ? '生成并对比候选' : '生成提示词候选' }}</v-btn><span v-if="form.config.analysis_prompt_template" class="text-caption text-medium-emphasis">当前已使用专属提示词</span><span v-else class="text-caption text-warning">请先生成并应用一份专属提示词后保存</span></div><v-row v-if="promptCandidates.length" class="mt-1"><v-col v-for="candidate in promptCandidates" :key="candidate.model" cols="12" :md="promptCandidates.length > 1 ? 6 : 12"><v-card variant="outlined" class="prompt-candidate h-100"><v-card-text><div class="d-flex align-center justify-space-between ga-3"><div><strong>{{ candidate.model }}</strong><p v-if="candidate.summary">{{ candidate.summary }}</p></div><v-btn color="success" size="small" @click="applyPromptCandidate(candidate)">应用此候选</v-btn></div><v-alert v-if="candidate.assumptions?.length" type="info" variant="tonal" density="compact" class="my-3">{{ candidate.assumptions.join('；') }}</v-alert><details><summary>查看生成的 System Prompt 与分析模板</summary><pre>{{ candidate.system_prompt }}\n\n---\n\n{{ candidate.analysis_prompt_template }}</pre></details></v-card-text></v-card></v-col></v-row></div></v-col>
        <v-col cols="12"><v-switch v-model="form.share_runtime_data" color="success" inset label="共享运行数据" hint="仅共享分析结论和可见参数，不共享提示词与模型配置。" persistent-hint/></v-col>
      </v-row></v-card-text>
      <v-card-actions><v-spacer/><v-btn variant="text" @click="dialog=false">取消</v-btn><v-btn color="primary" :loading="saving" @click="save">保存</v-btn></v-card-actions>
    </v-card></v-dialog>
  </v-container>
</template>

<script setup>
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { marketAPI } from '@/api/market'

const periods = ['M1', 'M5', 'M15', 'H1', 'H4']
const defaultPromptIntent = '识别主周期趋势、行情状态、关键支撑压力位与可执行交易机会；趋势行情可顺势交易，区间震荡仅在支撑附近买入或压力附近卖出，区间中部及证据不足时不建议交易。'
const defaultSystemPrompt = '你是一位专业的技术分析师，擅长通过K线数据识别市场趋势、关键价位与交易机会。你只能依据主品种和主周期的给定K线数据作出判断；参考行情仅能辅助确认。只返回严格、完整的JSON对象，不得输出解释、推理过程或Markdown。'
const defaultAnalysisPromptTemplate = '请根据以下主行情K线数据进行分析：\n{{market_data}}\n\n当前可交易参考价：\n{{current_price}}\n\n请严格只返回一个JSON对象，顶层键必须是主品种名称，格式如下：\n{"主品种":{"trend_analysis":{"主周期":{"trend":"上涨|下跌|横盘","confidence":0,"reason":"基于K线的理由"}},"overall_trend":{"direction":"up|down|sideways","strength":0,"summary":"行情状态与结论"},"key_levels":{"resistance":[0],"support":[0]},"trade_suggestions":[{"signal_source_id":"当前信号源ID","period":"主周期","direction":"buy|sell","confidence":0,"entry_price":0,"stop_loss":0,"take_profit":0,"reason":"交易逻辑"}]}}\n\n交易建议必须以当前可交易参考价为基准，只有价格接近计划入场位才可输出。趋势行情可以给出顺势交易建议。横盘或区间震荡时，仅能在已验证支撑位附近给出 buy，或在已验证压力位附近给出 sell；区间中部或确认不足时，trade_suggestions 必须返回 []，不要勉强输出建议。所有价格必须由给定K线推导，买入必须满足 stop_loss < entry_price < take_profit，卖出必须满足 take_profit < entry_price < stop_loss。'
const defaultPromptCandidate = () => ({ model: 'BTC5MIN 默认候选', system_prompt: defaultSystemPrompt, analysis_prompt_template: defaultAnalysisPromptTemplate, summary: '基于 BTC5MIN 的趋势、关键价位和交易计划分析目标，已转换为策略可执行的输出格式。', assumptions: ['只分析主品种和主周期', '仅在主周期K线数量充足时生成分析', '无明确机会时不输出交易建议'] })
const sources = ref([]), loading = ref(false), saving = ref(false), dialog = ref(false), message = ref(''), messageType = ref('success'), loadingOptions = ref(false), generatingPrompt = ref(false), promptIntent = ref(defaultPromptIntent), promptModels = ref([]), promptCandidates = ref([])
const options = reactive({ models: [], promptGenerationModels: [], symbols: [], marketDataAccounts: [], system: '', prompt: '', runtimeContract: { runtime_variables: [], output_contract: {}, strategy_usage: [] } })
const emptyForm = () => ({ signal_source_id: '', name: '', market_data_account_id: null, symbol: '', period: 'M5', enabled: true, share_runtime_data: false, config: { analysis_mode: 'self_analysis', model: '', analysis_interval_minutes: 5, kline_count: 288, prompt_mode: 'custom', reference_runtime_ids: [], reference_market_data: [], system_prompt: defaultSystemPrompt, analysis_prompt_template: defaultAnalysisPromptTemplate } })
const form = reactive(emptyForm())
const intervalOptions = computed(() => [1,2,3,5,10,15,30,60,120,240,480,720,1440].filter(value => value >= ({ M1: 1, M5: 5, M15: 15, H1: 60, H4: 240 }[form.period] || 1)).map(value => ({ title: `${value} 分钟`, value })))
const referenceRoles = [{ title: '高周期确认', value: 'higher_timeframe' }, { title: '低周期确认', value: 'lower_timeframe' }, { title: '相关品种', value: 'related_symbol' }, { title: '市场上下文', value: 'market_context' }]
const references = computed(() => form.config.reference_market_data || [])
// 同品种的其他周期也是有效的参考行情；只有同品种时排除主分析周期。
const referenceSymbols = computed(() => Array.from(new Set([form.symbol, ...options.symbols].filter(Boolean))))
function referencePeriodOptions (reference) {
  const current = String(reference?.period || '')
  const isSameSymbol = String(reference?.symbol || '').trim().toUpperCase() === String(form.symbol || '').trim().toUpperCase()
  return periods.filter(period => !isSameSymbol || period !== form.period || period === current)
}
const canGeneratePrompt = computed(() => Boolean(form.symbol && form.period && promptIntent.value.trim() && promptModels.value.length <= 3))
const clone = value => JSON.parse(JSON.stringify(value))
async function load () { loading.value = true; try { sources.value = (await marketAPI.getAISignalSources()).items || [] } catch (e) { messageType.value='error'; message.value=e.response?.data?.detail || '加载信号源失败' } finally { loading.value=false } }
async function loadOptions () { loadingOptions.value=true; try { const data=await marketAPI.getLLMSignalOptions(form.symbol || null); options.models=data.models||[]; options.promptGenerationModels=data.prompt_generation_models||[]; options.symbols=data.symbols||[]; options.marketDataAccounts=data.market_data_accounts||[]; if (!form.market_data_account_id) form.market_data_account_id=options.marketDataAccounts[0]?.value || null; options.system=data.default_system_prompt||''; options.prompt=data.default_analysis_prompt_template||''; options.runtimeContract=data.runtime_contract || { runtime_variables: [], output_contract: {}, strategy_usage: [] } } finally { loadingOptions.value=false } }
function openCreate () { Object.assign(form, emptyForm()); promptIntent.value=defaultPromptIntent; promptModels.value=[]; promptCandidates.value=[defaultPromptCandidate()]; dialog.value=true; loadOptions() }
function openEdit (item) { Object.assign(form, clone(item)); form.config ||= {}; form.config.reference_market_data ||= []; form.config.prompt_mode='custom'; promptIntent.value=defaultPromptIntent; promptModels.value=[]; const currentCandidate = form.config.system_prompt && form.config.analysis_prompt_template ? { model: '已确认提示词', system_prompt: form.config.system_prompt, analysis_prompt_template: form.config.analysis_prompt_template, summary: '此信号源当前保存并正在使用的专属提示词。', assumptions: [] } : null; promptCandidates.value=currentCandidate ? [currentCandidate] : [defaultPromptCandidate()]; dialog.value=true; loadOptions() }
function normalizeReferencePeriod (reference) {
  if (!reference || String(reference.symbol || '').trim().toUpperCase() !== String(form.symbol || '').trim().toUpperCase()) return
  if (reference.period !== form.period) return
  reference.period = periods.find(period => period !== form.period) || form.period
}
function addReference () {
  if (references.value.length >= 5) return
  const symbol = form.symbol || referenceSymbols.value[0] || ''
  const period = periods.find(value => value !== form.period) || form.period
  references.value.push({ symbol, period, kline_count: 100, role: 'market_context' })
}
function removeReference (index) { references.value.splice(index, 1) }
async function generatePrompt () { generatingPrompt.value=true; try { const data=clone(form); data.config.reference_market_data=(data.config.reference_market_data || []).filter(item => item.symbol && item.period); const result=await marketAPI.generateAISignalPrompt({ ...data, intent: promptIntent.value.trim(), model_ids: promptModels.value }); promptCandidates.value=result.candidates || (result.candidate ? [result.candidate] : []); messageType.value='success'; message.value=promptCandidates.value.length > 1 ? '已生成多个提示词候选，请对比后选择一份应用。' : '已根据当前信号源配置生成候选提示词，请预览后应用。' } catch(e) { messageType.value='error'; message.value=e.response?.data?.detail || '生成提示词候选失败' } finally { generatingPrompt.value=false } }
function applyPromptCandidate (candidate) { if (!candidate) return; form.config.prompt_mode='custom'; form.config.system_prompt=candidate.system_prompt; form.config.analysis_prompt_template=candidate.analysis_prompt_template; messageType.value='success'; message.value=`已应用 ${candidate.model || '候选'}，保存信号源后生效。` }
async function save () { saving.value=true; try { const data=clone(form); const minimum={M1:1,M5:5,M15:15,H1:60,H4:240}[data.period]||1; data.config.analysis_mode='self_analysis'; data.config.analysis_interval_minutes=Math.max(minimum, Number(data.config.analysis_interval_minutes) || 0); data.config.kline_count=Math.max(10, Math.min(288, Number(data.config.kline_count) || 100)); data.config.reference_market_data=(data.config.reference_market_data || []).filter(item => item.symbol && item.period).map(item => ({ ...item, kline_count: Math.max(10, Math.min(288, Number(item.kline_count) || 100)) })); data.config.prompt_mode='custom'; if (!data.config.system_prompt || !data.config.analysis_prompt_template) throw new Error('请先生成并应用一份专属提示词候选'); const result=data.signal_source_id ? await marketAPI.updateAISignalSource(data.signal_source_id,data) : await marketAPI.createAISignalSource(data); dialog.value=false; messageType.value='success'; message.value=result.source?.locked ? '已保存并冻结' : 'AI 信号源已保存'; await load() } catch(e) { messageType.value='error'; message.value=e.response?.data?.detail || '保存失败' } finally { saving.value=false } }
async function copy (item) { try { await marketAPI.copyAISignalSource(item.signal_source_id); messageType.value='success'; message.value='已创建可修改的新副本'; await load() } catch(e) { messageType.value='error'; message.value=e.response?.data?.detail || '复制失败' } }
async function remove (item) { if (!confirm(`删除“${item.name}”吗？`)) return; try { await marketAPI.deleteAISignalSource(item.signal_source_id); await load() } catch(e) { messageType.value='error'; message.value=e.response?.data?.detail || '删除失败' } }
watch(() => form.period, () => { const minimum={M1:1,M5:5,M15:15,H1:60,H4:240}[form.period]||1; form.config.analysis_interval_minutes=Math.max(Number(form.config.analysis_interval_minutes)||0, minimum) })
onMounted(load)
</script>

<style scoped>
.page{max-width:1500px;padding:28px}.hero{display:flex;align-items:center;justify-content:space-between;gap:24px;padding:28px 30px;border-radius:22px;color:#f7fcfa;background:radial-gradient(circle at 84% 16%,rgba(249,193,78,.3),transparent 26%),linear-gradient(125deg,#153e36,#13735c)}.hero span,.eyebrow{font-size:.72rem;font-weight:800;letter-spacing:.14em;color:#f2c768}.hero h1{margin:4px 0 7px;font-size:2.35rem}.hero p{margin:0;color:rgba(255,255,255,.78)}.source-card{height:100%;border:1px solid #dbe8e1;border-radius:18px;background:linear-gradient(145deg,#fff,#f7fbf8)}.source-card h2{margin:4px 0 8px;font-size:1.25rem;color:#1f4f42}.source-card p{min-height:38px;color:#60736b;font-size:.84rem}.chips{display:flex;flex-wrap:wrap;gap:6px}.lock-note{min-height:0!important;color:#9b6818!important}.empty{padding:90px 20px;text-align:center;color:#60736b}.empty h2{color:#294f42}.reference-header{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;padding-top:8px}.section-label{font-weight:700;color:#315f50}.reference-help{margin-top:4px;color:#71837b;font-size:.82rem}.reference-row{display:grid;grid-template-columns:1.2fr .8fr .8fr 1fr auto;gap:10px;align-items:center;padding:12px;border:1px solid #dce9e2;border-radius:12px;background:#f7fbf8}.prompt-builder{padding:16px;border:1px solid #dce9e2;border-radius:14px;background:linear-gradient(145deg,#fbfdfb,#f1f8f4)}.runtime-contract{line-height:1.45}.contract-title{font-weight:700;margin-bottom:6px}.contract-row{display:flex;gap:8px;margin-top:5px;align-items:flex-start}.contract-row code{white-space:nowrap;font-weight:700}.contract-row strong{white-space:nowrap}.prompt-candidate p{margin:4px 0 0;color:#60736b;font-size:.82rem}.prompt-candidate summary{cursor:pointer;color:#1f6a52;font-size:.82rem;font-weight:700}.prompt-candidate pre{max-height:260px;overflow:auto;padding:12px;border-radius:10px;background:#102c24;color:#e0f3e9;font-size:.72rem;white-space:pre-wrap}@media(max-width:850px){.reference-row{grid-template-columns:1fr 1fr}.reference-row .v-btn{justify-self:end}}@media(max-width:700px){.page{padding:16px}.hero{align-items:stretch;flex-direction:column}.hero h1{font-size:1.9rem}.contract-row{display:block}.contract-row code,.contract-row strong{display:block;margin-bottom:2px}}
</style>
