<template>
  <v-container fluid class="structure-page">
    <section class="hero">
      <div><span>MARKET STRUCTURE</span><h1>{{ symbol }} · {{ period }} 结构分析</h1><p>连续滑动识别行情结构，保留最近 5 个已确认结构段。</p></div>
      <div class="controls"><v-select v-model="symbol" :items="symbols" label="品种" density="compact" hide-details variant="outlined"/><v-select v-model="period" :items="periods" label="周期" density="compact" hide-details variant="outlined"/><v-btn color="primary" :loading="loading" @click="load">刷新</v-btn></div>
    </section>
    <v-alert v-if="error" type="error" variant="tonal" class="mb-4">{{ error }}</v-alert>
    <v-card v-if="bars.length" class="chart-card mb-4"><v-card-title>K线与结构段</v-card-title><v-card-text><div ref="chartRef" class="chart" style="height:480px;width:100%"></div><div class="legend"><span v-for="type in ['up','sideways','down','transition']" :key="type"><i :style="{background:legendColors[type]}"></i>{{ labels[type] }}</span></div></v-card-text></v-card>
    <v-row v-if="structureResult">
      <v-col cols="12" md="4"><v-card class="summary"><v-card-text><small>后端结构状态</small><h2>{{ stateLabel(structureResult.current_state) }}</h2><div class="stats"><span>ATR {{ Number(structureResult.atr || 0).toFixed(2) }}</span><span>摆动点 {{ structureResult.swings?.length || 0 }}</span></div></v-card-text></v-card></v-col>
      <v-col cols="12" md="8"><v-card class="summary"><v-card-title>结构事件</v-card-title><v-card-text><div class="event-list"><span v-for="(event,index) in recentEvents" :key="`event-${index}`" :class="event.direction==='up'?'event-up':'event-down'">{{ event.type?.toUpperCase() }} · {{ event.direction==='up'?'向上':'向下' }} · {{ event.level ? Number(event.level).toFixed(2) : '流动性扫过' }} · {{ barStamp(event.index) }}</span><span v-if="!recentEvents.length" class="empty">暂无已确认结构事件</span></div></v-card-text></v-card></v-col>
    </v-row>
    <v-card class="mb-4 llm-card" :loading="llmLoading">
      <v-card-title class="d-flex align-center justify-space-between">
        <span>大模型结构识别</span>
        <v-chip v-if="llmResult?.status" size="small" :color="llmStatusColor(llmResult.status)" variant="tonal">{{ llmStatusLabel(llmResult.status) }}</v-chip>
      </v-card-title>
      <v-card-text v-if="llmResult && !['error','queued','running'].includes(llmResult.status)">
        <div class="llm-summary"><strong>{{ llmLabel(llmResult.current_structure) || '未明确' }}</strong><span>{{ llmResult.analyzed_at ? formatDate(llmResult.analyzed_at) : '' }}</span></div>
        <p class="llm-text">{{ llmResult.summary || '模型未返回摘要' }}</p>
        <div v-if="normalizedLLMSegments.length" class="timeline llm-timeline">
          <div v-for="(item,index) in normalizedLLMSegments" :key="`llm-${index}`" class="segment">
            <i :style="{background:llmColor(item.type)}"></i><div><strong>{{ llmLabel(item.type) }}</strong><small>{{ item.start_time || item.start || '--' }} → {{ item.end_time || item.end || '--' }} · {{ item.bar_count || item.bars || 0 }} 根</small><p>{{ item.reason || '' }}</p></div>
          </div>
        </div>
      </v-card-text>
      <v-card-text v-else-if="llmResult?.status === 'error'" class="text-error">大模型分析失败：{{ llmResult.error }}</v-card-text>
      <v-card-text v-else-if="llmResult?.status === 'queued' || llmResult?.status === 'running'" class="empty">{{ llmStatusLabel(llmResult.status) }}，最近触发时间：{{ formatDate(llmResult.queued_at || llmResult.started_at) }}</v-card-text>
      <v-card-text v-else class="empty">暂无大模型结构分析结果</v-card-text>
    </v-card>
    <v-row v-if="current">
      <v-col cols="12" md="4"><v-card class="summary"><v-card-text><small>当前结构</small><h2>{{ labels[current.type] || current.type }}</h2><v-chip :color="colors[current.type] || 'grey'" variant="tonal">{{ current.status }}</v-chip><p>{{ current.reason }}</p><div class="stats"><span>持续 {{ current.bars }} 根K线</span><span>置信度 {{ current.confidence }}%</span></div></v-card-text></v-card></v-col>
      <v-col cols="12" md="8"><v-card class="summary"><v-card-title>结构变化时间线</v-card-title><v-card-text><div class="timeline"><div v-for="(item,index) in segments" :key="item.id" class="segment" :class="{active:index===segments.length-1}"><i :style="{background:legendColors[item.type]||'#78909c'}"></i><div><strong>{{ labels[item.type] || item.type }}</strong><small>{{ item.start }} → {{ item.end }} · {{ item.bars }} 根</small><p>{{ item.reason }}</p></div></div></div></v-card-text></v-card></v-col>
    </v-row>
    <v-card v-if="segments.length" class="mt-4"><v-card-title>最近 5 个结构段</v-card-title><v-card-text><div class="segment-grid"><article v-for="item in segments" :key="`card-${item.id}`" :class="{active:item.id===current?.id}"><div class="card-head"><v-chip size="small" :color="colors[item.type]||'grey'" variant="tonal">{{ labels[item.type]||item.type }}</v-chip><span>{{ item.bars }} 根</span></div><strong>{{ item.start }} → {{ item.end }}</strong><p>{{ item.reason }}</p><small>支撑 {{ item.support.toFixed(2) }} · 压力 {{ item.resistance.toFixed(2) }}</small></article></div></v-card-text></v-card>
    <v-card v-else-if="!loading" class="empty mt-4"><v-card-text>暂无足够 K 线识别结构</v-card-text></v-card>
  </v-container>
</template>

<script setup>
import { computed, nextTick, onMounted, onUnmounted, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { marketAPI } from '../api/market'
import * as echarts from 'echarts'

const route = useRoute(); const symbol = ref(String(route.query.symbol || 'BTCUSD')); const period = ref(String(route.query.period || 'M5')); const periods=['M1','M5','M15','H1','H4']; const symbols=ref([symbol.value]); const loading=ref(false); const llmLoading=ref(false); const error=ref(''); const segments=ref([]); const bars=ref([]); const structureResult=ref(null); const llmResult=ref(null); const chartRef=ref(null); let chart=null
const labels={up:'上涨趋势',down:'下跌趋势',sideways:'箱体震荡',transition:'结构过渡'}; const colors={up:'success',down:'error',sideways:'info',transition:'warning'}; const legendColors={up:'#3aa675',down:'#d95d55',sideways:'#4f91c4',transition:'#d4a24c'}
const closeOf=x=>Number(x.close ?? x.close_price ?? 0); const timeOf=x=>{const raw=x?.timestamp??x?.time??0;if(typeof raw==='number')return raw>1e12?raw:raw*1000;const parsed=Date.parse(raw);return Number.isFinite(parsed)?parsed:0}; const stamp=x=>new Date(timeOf(x)).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})
function swings(rows){const out=[];const span=Math.max(2,Math.floor(rows.length/45));for(let i=span;i<rows.length-span;i++){const h=Number(rows[i].high??rows[i].high_price??closeOf(rows[i]));const l=Number(rows[i].low??rows[i].low_price??closeOf(rows[i]));const left=rows.slice(i-span,i).map(x=>Number(x.high??x.high_price??closeOf(x)));const right=rows.slice(i+1,i+span+1).map(x=>Number(x.high??x.high_price??closeOf(x)));const ll=rows.slice(i-span,i).map(x=>Number(x.low??x.low_price??closeOf(x)));const lr=rows.slice(i+1,i+span+1).map(x=>Number(x.low??x.low_price??closeOf(x)));if(h>=Math.max(...left,...right))out.push({index:i,type:'high',price:h});if(l<=Math.min(...ll,...lr))out.push({index:i,type:'low',price:l})}return out}
function classify(rows){if(rows.length<12)return 'transition';const sw=swings(rows), highs=sw.filter(x=>x.type==='high').slice(-5), lows=sw.filter(x=>x.type==='low').slice(-5);if(highs.length<3||lows.length<3)return'transition';const dh=highs.slice(-3).map((x,i,a)=>i?x.price-a[i-1].price:0).slice(1), dl=lows.slice(-3).map((x,i,a)=>i?x.price-a[i-1].price:0).slice(1);const scale=Math.max(1,Math.max(...rows.map(x=>Number(x.high??x.high_price??closeOf(x))))-Math.min(...rows.map(x=>Number(x.low??x.low_price??closeOf(x)))));const nh=(dh[0]+dh[1])/(2*scale),nl=(dl[0]+dl[1])/(2*scale);const rangeHigh=Math.max(...highs.map(x=>x.price)),rangeLow=Math.min(...lows.map(x=>x.price));const closes=rows.map(closeOf);const tail=closes.slice(-3);const upBreak=tail.every(v=>v>rangeHigh*1.0003),downBreak=tail.every(v=>v<rangeLow*0.9997);if(upBreak)return'up';if(downBreak)return'down';if(nh>.003&&nl>.003&&dh.every(v=>v>0)&&dl.every(v=>v>0))return'up';if(nh<-.003&&nl<-.003&&dh.every(v=>v<0)&&dl.every(v=>v<0))return'down';if(Math.abs(nh)<.004&&Math.abs(nl)<.004){const touches=sw.filter(x=>(x.type==='high'&&Math.abs(x.price-rangeHigh)/rangeHigh<.003)||(x.type==='low'&&Math.abs(x.price-rangeLow)/rangeLow<.003)).length;if(touches>=3)return'sideways'}return'transition'}
/* legacy build retained below for reference */
function build(rows){
  const step=Math.max(5,Math.floor(rows.length/60)); const window=Math.max(30,step*4); const raw=[];
  for(let i=0;i<rows.length;i+=step){const end=Math.min(rows.length,i+window);raw.push({i,end,type:classify(rows.slice(i,end))})}
  const confirmed=[];
  raw.forEach((item,index)=>{const last=confirmed.at(-1);if(!last){confirmed.push({type:item.type,startIndex:item.i,endIndex:item.end-1});return}if(item.type===last.type){last.endIndex=item.end-1;return}if(raw[index+1]?.type===item.type){confirmed.push({type:item.type,startIndex:item.i,endIndex:item.end-1})}else last.endIndex=item.end-1});
  confirmed.forEach((s,i)=>{s.endIndex=i+1<confirmed.length?confirmed[i+1].startIndex-1:rows.length-1});
  // 先识别趋势破坏：高点/低点后的深度回撤应切段，即使反向段尚未很长。
  const broken=[]; for(const s of confirmed){const part=rows.slice(s.startIndex,s.endIndex+1); if((s.type==='up'||s.type==='down')&&part.length>=Math.max(24,step*4)){const vals=part.map(closeOf); const extreme=s.type==='up'?Math.max(...vals):Math.min(...vals); const at=s.type==='up'?vals.lastIndexOf(extreme):vals.lastIndexOf(extreme); const tail=vals.slice(at+1); const span=Math.max(...vals)-Math.min(...vals); const retrace=span?Math.abs((tail.at(-1)||extreme)-extreme)/span:0; const recent=tail.slice(-Math.max(4,step)).filter((v,i,a)=>s.type==='up'?v<=a[Math.max(0,i-1)]:v>=a[Math.max(0,i-1)]).length; if(at>=8&&tail.length>=Math.max(8,step*2)&&retrace>=0.42&&recent>=Math.max(3,step-1)){const cut=s.startIndex+at+1; broken.push({...s,endIndex:cut-1}); broken.push({type:s.type==='up'?'down':'up',startIndex:cut,endIndex:s.endIndex}); continue}} broken.push(s)}
  // 普通反向短段仍需至少 4 个采样步长，避免单次噪声造成切换。
  // 校正窗口内的明显拐点：若下跌段先上涨创高，再持续回落，起点应落在高点确认处。
  const corrected=[]; for(const s of broken){const part=rows.slice(s.startIndex,s.endIndex+1); const vals=part.map(closeOf); const span=Math.max(...vals)-Math.min(...vals); if(vals.length>=20&&span>0&&(s.type==='down'||s.type==='up')){const extreme=s.type==='down'?Math.max(...vals):Math.min(...vals); const pivot=vals.lastIndexOf(extreme); const lead=s.type==='down'?vals[pivot]-vals[0]:vals[0]-vals[pivot]; if(pivot>=5&&pivot<=vals.length*.9&&lead/span>=.15&&vals.length-pivot>=6){corrected.push({type:s.type==='down'?'up':'down',startIndex:s.startIndex,endIndex:s.startIndex+pivot}); corrected.push({...s,startIndex:s.startIndex+pivot+1}); continue}} corrected.push(s)}
  const merged=[]; for(const s of corrected){const last=merged.at(-1);if(last&&last.type!==s.type&&s.endIndex-s.startIndex+1<step*3)last.endIndex=s.endIndex;else if(last&&last.type===s.type)last.endIndex=s.endIndex;else merged.push(s)}
  return merged.slice(-5).map((s,i,arr)=>{const part=rows.slice(s.startIndex,s.endIndex+1);return {...s,id:`s-${s.startIndex}`,bars:part.length,start:stamp(part[0]),end:stamp(part.at(-1)),support:Math.min(...part.map(x=>Number(x.low??x.low_price??closeOf(x)))),resistance:Math.max(...part.map(x=>Number(x.high??x.high_price??closeOf(x)))),confidence:s.type==='transition'?50:70,status:i===arr.length-1?'当前已确认':'已结束',reason:s.type==='up'?'高低点和收盘结构持续抬升（允许中途震荡/回撤）':s.type==='down'?'高低点和收盘结构持续下移（允许中途震荡/反弹）':s.type==='sideways'?'价格在区间内反复运行':'趋势证据发生冲突，等待确认'}})
}
const current=computed(()=>segments.value.at(-1))
const llmLabel=type=>({uptrend:'上涨趋势',downtrend:'下跌趋势',range:'箱体震荡',range_rising:'震荡上升',range_falling:'震荡下降',breakout:'突破',transition:'结构过渡'}[String(type||'').toLowerCase()]||type||'')
const llmStatusLabel=value=>({queued:'排队中',running:'分析中',ok:'分析完成',error:'分析失败'}[String(value||'')]||'暂无结果')
const llmStatusColor=value=>({queued:'warning',running:'info',ok:'success',error:'error'}[String(value||'')]||'grey')
const llmColor=type=>({uptrend:'#3aa675',downtrend:'#d95d55',range:'#4f91c4',range_rising:'#4f91c4',range_falling:'#4f91c4',breakout:'#9b6dcc',transition:'#d4a24c'}[String(type||'').toLowerCase()]||'#78909c')
const normalizedLLMSegments=computed(()=>Array.isArray(llmResult.value?.segments)?llmResult.value.segments:[])
const formatDate=value=>{const d=new Date(value);return Number.isNaN(d.getTime())?'':d.toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})}
const stateLabel=value=>({bullish:'上涨趋势',bearish:'下跌趋势',undetermined:'尚未确认'}[value]||'结构过渡')
const barStamp=index=>bars.value[index]?stamp(bars.value[index]):''
const recentEvents=computed(()=>Array.isArray(structureResult.value?.events)?structureResult.value.events.slice(-10).reverse():[])
function renderChart(){
  if(!chartRef.value||!bars.value.length)return
  if(chart)chart.dispose(); chart=echarts.init(chartRef.value)
  const rows=bars.value; const result=structureResult.value||{}
  const data=rows.map(x=>[Number(x.open??x.open_price??closeOf(x)),Number(x.close??x.close_price??0),Number(x.low??x.low_price??closeOf(x)),Number(x.high??x.high_price??closeOf(x))])
  const area=segments.value.map(s=>[{name:labels[s.type],xAxis:s.startIndex,itemStyle:{color:`rgba(${s.type==='up'?'58,166,117':s.type==='down'?'217,93,85':s.type==='sideways'?'79,145,196':'212,162,76'},0.14)`}},{xAxis:s.endIndex}])
  const pivots=Array.isArray(result.swings)?result.swings:[]
  const pivotMarks=pivots.filter(p=>Number.isInteger(p.index)&&p.index>=0&&p.index<rows.length).map(p=>({coord:[p.index,Number(p.price)],value:p.label|| (p.kind==='high'?'H':'L'),name:p.label||p.kind,itemStyle:{color:p.kind==='high'?'#c84f43':'#287a60'}}))
  const eventMarks=(Array.isArray(result.events)?result.events:[]).filter(e=>Number.isInteger(e.index)&&e.index>=0&&e.index<rows.length).map(e=>({value:[e.index,Number(e.level||closeOf(rows[e.index]))],event:e,valueLabel:e.type==='liquidity_sweep'?'扫':'BOS/CHoCH',name:e.type,itemStyle:{color:e.direction==='up'?'#16845f':'#c84f43'}}))
  const trend=(Array.isArray(result.trendlines)?result.trendlines:[]).map((line,n)=>({type:'line',name:`${line.kind==='support'?'上涨支撑':'下降压力'} · ${line.level||''}`,data:rows.map((_,i)=>i<line.start_index||i>line.end_index?'-':Number(line.start_price)+(Number(line.slope)||0)*(i-Number(line.start_index))),symbol:'none',lineStyle:{color:line.kind==='support'?'#2b9b72':'#d95d55',type:'dashed',width:2},showSymbol:false,connectNulls:false,z:3}))
  const range=result.range?.active?[{name:'箱体上沿',yAxis:Number(result.range.top)},{name:'箱体下沿',yAxis:Number(result.range.bottom)}]:[]
  const eventLines=(Array.isArray(result.events)?result.events:[]).filter(e=>Number.isInteger(e.index)).map(e=>({name:e.type==='choch'?'CHoCH':e.type==='bos'?'BOS':'流动性扫过',xAxis:e.index,lineStyle:{color:e.direction==='up'?'#16845f':'#c84f43',type:'dotted',width:1},label:{show:true,formatter:e.type==='liquidity_sweep'?'扫':e.type.toUpperCase(),color:e.direction==='up'?'#16845f':'#c84f43',fontSize:10}}))
  chart.setOption({animation:false,tooltip:{trigger:'axis',axisPointer:{type:'cross'}},legend:{top:0,type:'scroll'},grid:{left:55,right:35,top:38,bottom:58},xAxis:{type:'category',data:rows.map(stamp),axisLabel:{hideOverlap:true}},yAxis:{scale:true},dataZoom:[{type:'inside'},{type:'slider',height:18,bottom:8}],series:[{name:'K线',type:'candlestick',data,itemStyle:{color:'#1f9d72',color0:'#d95d55',borderColor:'#1f9d72',borderColor0:'#d95d55'},markArea:{silent:true,data:area},markPoint:{symbol:'circle',symbolSize:9,data:pivotMarks,label:{show:true,position:'top',fontSize:10,formatter:p=>p.value}},markLine:{silent:true,symbol:'none',data:[...range,...eventLines]}},...trend,{name:'突破/扫单',type:'scatter',data:eventMarks,symbol:'pin',symbolSize:30,label:{show:true,formatter:p=>p.data.valueLabel,color:'#fff',fontSize:9},z:8}]},true)
  window.addEventListener('resize',resizeChart)
}
function resizeChart(){chart?.resize()}
async function loadLLMResult(){llmLoading.value=true;try{const res=await marketAPI.getStructureAnalysisResults();const items=Array.isArray(res?.items)?res.items:[];llmResult.value=items.filter(item=>String(item.symbol||'').toUpperCase()===symbol.value.toUpperCase()&&String(item.period||'').toUpperCase()===period.value.toUpperCase()).sort((a,b)=>String(b.analyzed_at||'').localeCompare(String(a.analyzed_at||'')))[0]||null}catch(e){llmResult.value=null}finally{llmLoading.value=false}}
async function load(){loading.value=true;error.value='';try{const res=await marketAPI.getKlines(symbol.value,period.value,600);const raw=Array.isArray(res?.data)?res.data:(Array.isArray(res?.klines)?res.klines:(Array.isArray(res?.data?.klines)?res.data.klines:[]));const rows=raw.slice().sort((a,b)=>timeOf(a)-timeOf(b));bars.value=rows;const sr=await marketAPI.getMarketStructure(symbol.value,period.value,600);const backend=sr?.data;structureResult.value=backend||null;if(Array.isArray(backend?.segments)&&backend.segments.length){segments.value=backend.segments.slice(-5).map((s,i)=>{const p=rows.slice(s.start_index,s.end_index+1);return {...s,id:`backend-${s.start_index}`,type:s.type,bars:p.length,start:stamp(p[0]),end:stamp(p.at(-1)),support:Math.min(...p.map(x=>Number(x.low??x.low_price??closeOf(x)))),resistance:Math.max(...p.map(x=>Number(x.high??x.high_price??closeOf(x)))),confidence:70,status:i===Math.min(backend.segments.length,5)-1?'当前已确认':'已结束',reason:s.event?`${s.event.type.toUpperCase()} ${s.event.direction==='up'?'向上':'向下'}结构确认`:'基于摆动高低点结构'}})}else segments.value=build(rows);await nextTick();renderChart();await loadLLMResult()}catch(e){error.value=e?.response?.data?.detail||'结构数据加载失败'}finally{loading.value=false}}
async function loadSymbols(){try{const res=await marketAPI.getSymbols();const values=(res?.symbols||res?.data||[]).map(item=>typeof item==='string'?item:(item.symbol||item.value||'')).filter(Boolean);symbols.value=Array.from(new Set([symbol.value,...values]))}catch(e){/* 保留当前品种，行情接口失败不阻断页面 */}}
watch(period,load);watch(symbol,load);onMounted(async()=>{await loadSymbols();await load()});onUnmounted(()=>{window.removeEventListener('resize',resizeChart);chart?.dispose()})
</script>

<style scoped>.structure-page{max-width:1500px;padding:28px}.hero{display:flex;justify-content:space-between;gap:24px;align-items:center;padding:28px 30px;margin-bottom:20px;border-radius:22px;color:#f5fffa;background:linear-gradient(125deg,#173d35,#277d61)}.hero span{font-size:.72rem;letter-spacing:.16em;color:#f4cf77;font-weight:800}.hero h1{margin:5px 0;font-size:2rem}.hero p{margin:0;color:#cce4da}.controls{display:flex;gap:10px;align-items:center;min-width:390px}.summary{height:100%;border:1px solid #dbe8e1}.summary h2{margin:6px 0 10px;color:#204f42}.summary p{color:#60736b;min-height:34px}.stats{display:flex;gap:18px;color:#60736b;font-size:.85rem}.timeline{display:flex;gap:18px;overflow:auto;padding:8px 0}.segment{display:flex;gap:8px;min-width:150px}.segment i{width:8px;border-radius:8px;display:block}.segment small,.segment p{display:block;color:#71837b;font-size:.78rem;margin:4px 0}.segment.active strong{color:#167052}.segment-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:12px}.segment-grid article{padding:14px;border:1px solid #dbe8e1;border-radius:14px;background:#fbfdfb}.segment-grid article.active{border-color:#2d9871;box-shadow:0 5px 18px #2d987122}.card-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:10px}.segment-grid p{height:38px;color:#60736b;font-size:.82rem}.segment-grid small{color:#71837b}.empty{text-align:center;color:#71837b}@media(max-width:850px){.hero{align-items:stretch;flex-direction:column}.controls{min-width:0;width:100%}.segment-grid{grid-template-columns:1fr 1fr}}@media(max-width:600px){.structure-page{padding:16px}.controls{flex-wrap:wrap}.controls>*{flex:1}.segment-grid{grid-template-columns:1fr}}</style>
